<script setup lang="ts">
import { legal } from '~/lib/legal'
import { useSeo } from '~/lib/seo'
useSeo({
  title: 'Privacy',
  description:
    "stratless runs on your machine. No server, no account, no API key, no telemetry. We receive nothing, because there is nowhere for it to go.",
  path: '/privacy',
})
</script>

<template>
  <section class="section legal">
    <div class="container">
      <div class="legal-body prose">
        <h1>Privacy Policy</h1>
        <p class="eff">Effective {{ legal.effectiveDate }}</p>

        <p>
          <strong>stratless is a program that runs on your computer.</strong> It is not a service.
          There is no server, no account, no sign-up, and no API key. We do not receive your code,
          your conversations, or any information about you — because there is nowhere for it to go.
        </p>

        <h2>What stratless reads</h2>
        <p>
          Your coding assistant's own conversation history, which is already on your disk (Claude
          Code stores it in <code>~/.claude/projects</code>), and the files in the repository you
          run it against. It reads them. <strong>It does not send them anywhere.</strong>
        </p>

        <h2>The one network call, and it isn't ours</h2>
        <p>
          The <em>“So what”</em> sentence — the plain-English consequence — is generated by
          <strong>the coding assistant you already have installed</strong>. stratless shells out to
          it (<code>claude -p</code>), on your own subscription or key, and that request goes to your
          assistant's provider exactly as it does when you use it normally.
        </p>
        <p>
          <strong>It never touches us.</strong> We ship no model, hold no key, and run no proxy. If
          you have no assistant installed, stratless simply skips that line and shows you the quoted
          history instead.
        </p>

        <h2>What we collect</h2>
        <p>
          <strong>Nothing.</strong> No telemetry, no analytics, no crash reports, no usage counters,
          no phone-home of any kind. This is not a promise we're asking you to take on trust —
          <a href="https://github.com/stratless-ai/stratless-cli" target="_blank" rel="noopener">the
          source is public and it's about 900 lines</a>. You can read the whole thing in an
          afternoon and confirm there is no network code in it.
        </p>

        <h2>This website</h2>
        <p>
          {{ legal.site }} is a static site on Cloudflare Pages. It sets no cookies and runs no
          analytics. Cloudflare processes standard request logs (IP address, user agent) as part of
          serving it, which is the same for any website.
        </p>

        <h2>Contact</h2>
        <p>
          <a :href="`mailto:${legal.email}`">{{ legal.email }}</a>
        </p>
      </div>
    </div>
  </section>
</template>

<style scoped>
.legal-body {
  max-width: 42rem;
}
.eff {
  color: var(--mid);
  font-size: 0.9rem;
}
</style>
